# Generated by Django 4.1.3 on 2022-11-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airlineID', models.IntegerField(unique=True)),
                ('airlineName', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airportID', models.IntegerField(unique=True)),
                ('airportName', models.CharField(max_length=30, unique=True)),
                ('airportState', models.CharField(max_length=30, unique=True)),
                ('airportCountry', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baggageCarousalNo', models.IntegerField(unique=True)),
                ('baggageStatus', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.IntegerField(unique=True)),
                ('employeeFirstName', models.CharField(max_length=30)),
                ('employeeLastName', models.CharField(max_length=30)),
                ('employeeEmail', models.CharField(max_length=50)),
                ('employeeType', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightCode', models.CharField(max_length=30, unique=True)),
                ('flightSource', models.CharField(max_length=30, unique=True)),
                ('flightDestination', models.CharField(max_length=30, unique=True)),
                ('flightArrival', models.DateTimeField()),
                ('flightDeparture', models.DateField()),
                ('flightStatus', models.CharField(max_length=30)),
                ('flightType', models.CharField(max_length=30)),
                ('flightLayoverTime', models.CharField(max_length=30)),
                ('flightNoOfStops', models.IntegerField()),
                ('flightGate', models.IntegerField(unique=True)),
                ('flightCarouselNo', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateNo', models.IntegerField(unique=True)),
                ('gateStatus', models.CharField(max_length=30)),
            ],
        ),
    ]
