# Generated by Django 4.1.3 on 2022-11-15 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baggage',
            old_name='baggageCarousalNo',
            new_name='baggageCarouselNo',
        ),
    ]
