# Generated by Django 4.1.3 on 2022-11-22 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_baggagecarousalno_baggage_baggagecarouselno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flightLayoverTime',
        ),
    ]
